FROM alpine
RUN "apt install curl tar"
RUN "curl https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.4.1/freesurfer-linux-ubuntu20_amd64-7.4.1.tar.gz"
CMD [ "tar -zxpf freesurfer-linux-ubuntu20_amd64-7.4.1.tar.gz" ]